apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - mariadb.yaml
  - redis.yaml
  - frappe.yaml
  - nginx.yaml
  - gateways.yaml
  - ingress.yaml

namespace: yam-agri-staging
